### ISSUE TITLE
On the WSL 2 Grafana dont starts

### ISSUE THREAD

**Issue by eabykov** [eabykov/keycloak-compose#4]

**Comment by Joshswooft** [comment]
Also having this issue on mac, when i comment out `network_mode: host` I can then connect on port 3000 but it causes other issues with trying to connect to prometheus from within grafana.

**Comment by viguice** [comment]
Hi,

Thanks for sharing your project; It is very useful. I am in the case where Grafana doesn't start. So, I am wondering if Traefik might help and could make the solution more robust and more flexible.

I have created a forke here: https://github.com/viguice/keycloak-traefik-grafana-compose but it is working yet. I get a "bad gateway" error. Maybe a stupid thing (a parameter somewhere or something in the headers to change). Can you have a look and tell me if it is a good idea. If yes, It will be great if, by any chance, you can help me to identify what has to be changed compared to your original project.

**Comment by eabykov** [comment]
@viguice for grafana replace `network_mode: host` with `ports` section

After that Grafana can be accessible from web, but Grafana cant access Keycloak from Grafana container 
```
keycloak-traefik-grafana-compose-grafana-1  | logger=context userId=0 orgId=0 uname= t=2023-05-13T09:56:24.441854021Z level=error msg=login.OAuthLogin(NewTransportWithCode) error="Post \"http://keycloak.localhost/realms/grafana/protocol/openid-connect/token\": dial tcp: lookup keycloak.localhost on 127.0.0.11:53: no such host"
```
